# Generated by Django 3.2.8 on 2021-10-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddress', models.CharField(blank=True, max_length=255, null=True, verbose_name='ip address')),
                ('root', models.CharField(blank=True, max_length=255, null=True, verbose_name='Root Username')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Root Password')),
                ('additionalUser', models.CharField(blank=True, max_length=255, null=True, verbose_name='Additional user')),
                ('additionalUser_passsword', models.CharField(blank=True, max_length=255, null=True, verbose_name="Additional User's password")),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
